### ISSUE TITLE
Problem in upgrading to version 3

### ISSUE THREAD

**Issue by erkanarslan** [EddyVerbruggen/nativescript-local-notifications#106]
I just upgraded plugin from version 2 to 3. I changed the code accordingly. But I get this error on runtime.

`TypeError: com.telerik.localnotifications.LocalNotificationsPlugin.scheduleNotification is not a function`

**Comment by EddyVerbruggen** [comment]
Remove the platforms/android folder and rebuild.

**Comment by damianocorrado** [comment]
Hi, i have the same issue when upgrade from version 2.x to 3.x
I have also removed platforms/node_nodules but nothing changes. The issue also occur on a fresh new project.

Console.log (LocalNotifications) returns an empty object so every methods called generate a runtime error. 

`TypeError: com.telerik.localnotifications.LocalNotificationsPlugin.scheduleNotification is not a function`

TNS version is 4.3 but even on 4.2 generate the same error.
Please consider a fix, this plugin is awesome and it's the only alternative to using notifications.
Thanks.

**Comment by EddyVerbruggen** [comment]
I'm using version 3 in 2 apps (1 Angular, and 1 core) on both iOS and Android without issues.

If you feel there's a problem please share a repo with me that shows the issue.
